# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rosst\Documents\Argo\Software\ui_Files\circulationapp.ui'
#
# Created: Tue Aug 23 08:39:04 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CirculationApp(object):
    def setupUi(self, CirculationApp):
        CirculationApp.setObjectName("CirculationApp")
        CirculationApp.resize(805, 584)
        self.verticalLayout = QtGui.QVBoxLayout(CirculationApp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.circulationStackedWidget = QtGui.QStackedWidget(CirculationApp)
        self.circulationStackedWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.circulationStackedWidget.setObjectName("circulationStackedWidget")
        self.settingsPage = QtGui.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.settingsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.label_8 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.label_16 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.label_9 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem4 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.label_17 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.label_3 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.centreOfPlotDateEdit = QtGui.QDateEdit(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.centreOfPlotDateEdit.setFont(font)
        self.centreOfPlotDateEdit.setCalendarPopup(True)
        self.centreOfPlotDateEdit.setDate(QtCore.QDate(2016, 7, 15))
        self.centreOfPlotDateEdit.setObjectName("centreOfPlotDateEdit")
        self.horizontalLayout_3.addWidget(self.centreOfPlotDateEdit)
        self.label_2 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sampleWindowBox = QtGui.QSpinBox(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sampleWindowBox.setFont(font)
        self.sampleWindowBox.setMinimum(1)
        self.sampleWindowBox.setMaximum(30)
        self.sampleWindowBox.setProperty("value", 15)
        self.sampleWindowBox.setObjectName("sampleWindowBox")
        self.horizontalLayout_9.addWidget(self.sampleWindowBox)
        self.label_7 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pressureCutOffBox = QtGui.QSpinBox(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pressureCutOffBox.setFont(font)
        self.pressureCutOffBox.setMaximum(2100)
        self.pressureCutOffBox.setProperty("value", 950)
        self.pressureCutOffBox.setObjectName("pressureCutOffBox")
        self.horizontalLayout_12.addWidget(self.pressureCutOffBox)
        self.label_10 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.pressureCutOffWarningLabel = QtGui.QLabel(self.settingsPage)
        self.pressureCutOffWarningLabel.setText("")
        self.pressureCutOffWarningLabel.setObjectName("pressureCutOffWarningLabel")
        self.horizontalLayout_12.addWidget(self.pressureCutOffWarningLabel)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.maxInterpDepthBox = QtGui.QSpinBox(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxInterpDepthBox.setFont(font)
        self.maxInterpDepthBox.setMaximum(99999)
        self.maxInterpDepthBox.setProperty("value", 1000)
        self.maxInterpDepthBox.setObjectName("maxInterpDepthBox")
        self.horizontalLayout_13.addWidget(self.maxInterpDepthBox)
        self.label_11 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        spacerItem10 = QtGui.QSpacerItem(53, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.stepSizeBox = QtGui.QSpinBox(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stepSizeBox.setFont(font)
        self.stepSizeBox.setMaximum(9999)
        self.stepSizeBox.setProperty("value", 5)
        self.stepSizeBox.setObjectName("stepSizeBox")
        self.horizontalLayout_13.addWidget(self.stepSizeBox)
        self.label_12 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.dynHeightAtPBox = QtGui.QSpinBox(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dynHeightAtPBox.setFont(font)
        self.dynHeightAtPBox.setMinimum(-9999)
        self.dynHeightAtPBox.setMaximum(9999)
        self.dynHeightAtPBox.setProperty("value", 0)
        self.dynHeightAtPBox.setObjectName("dynHeightAtPBox")
        self.horizontalLayout_14.addWidget(self.dynHeightAtPBox)
        self.label_13 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        spacerItem12 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.relativeToPrefBox = QtGui.QSpinBox(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.relativeToPrefBox.setFont(font)
        self.relativeToPrefBox.setMinimum(-9999)
        self.relativeToPrefBox.setMaximum(9999)
        self.relativeToPrefBox.setProperty("value", 1000)
        self.relativeToPrefBox.setObjectName("relativeToPrefBox")
        self.horizontalLayout_14.addWidget(self.relativeToPrefBox)
        self.label_18 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.totalModesBox = QtGui.QSpinBox(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalModesBox.setFont(font)
        self.totalModesBox.setMaximum(20)
        self.totalModesBox.setProperty("value", 20)
        self.totalModesBox.setObjectName("totalModesBox")
        self.horizontalLayout.addWidget(self.totalModesBox)
        self.label_4 = QtGui.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem15 = QtGui.QSpacerItem(20, 124, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.backButton_2 = QtGui.QPushButton(self.settingsPage)
        self.backButton_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton_2.setFont(font)
        self.backButton_2.setObjectName("backButton_2")
        self.horizontalLayout_8.addWidget(self.backButton_2)
        self.nextButton = QtGui.QPushButton(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_8.addWidget(self.nextButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.circulationStackedWidget.addWidget(self.settingsPage)
        self.calculatingPage = QtGui.QWidget()
        self.calculatingPage.setObjectName("calculatingPage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.calculatingPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.calculatingPage)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.circulationStackedWidget.addWidget(self.calculatingPage)
        self.verticalLayout.addWidget(self.circulationStackedWidget)

        self.retranslateUi(CirculationApp)
        self.circulationStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CirculationApp)

    def retranslateUi(self, CirculationApp):
        CirculationApp.setWindowTitle(QtGui.QApplication.translate("CirculationApp", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CirculationApp", "Program details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CirculationApp", "Start Latitude: 30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("CirculationApp", "End Latitude: 60", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CirculationApp", "Start Longitude: 180", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("CirculationApp", "End Longitude Point: 244", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CirculationApp", "Float Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CirculationApp", "Date of circulation plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CirculationApp", "Range of days used on both sides of target date to interpolate float data (Max 30)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CirculationApp", "Pressure Cut-Off (dbar)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CirculationApp", "Interpolate Vertically to Max Pressure  (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CirculationApp", "Step size for depth/pressure (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("CirculationApp", "Dynamic Heights at Surface (dbar)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("CirculationApp", "Relative to Level of No Motion (dbar)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CirculationApp", "Total number of modes to use in sum (max 20)", None, QtGui.QApplication.UnicodeUTF8))
        self.backButton_2.setText(QtGui.QApplication.translate("CirculationApp", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("CirculationApp", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CirculationApp", "Calculations in progress....", None, QtGui.QApplication.UnicodeUTF8))

